# Harmony Jekyll theme general configurations

# Base URL
baseurl:

# Site live URL
url: http://www.3manuek.com

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: 3manuek's Hub.
  # Little description about your site
  description: Databases, posts and service developing.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
    Emanuel Calvo is a Database Architect and Consultant.
    https://github.com/3manuek/
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Emanuel Calvo
    email: 3manuek@esdebian.org
    url: http://3manuek.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-76884172-1

  # Profile links, leave blank to ignore
  social:
    github: 3manuek
    twitter: 3manuek
    gplus: +3manuek
    #rstudio
    #pythian blog
    #linkedin
    #dribble: gayan
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

gems:
  - jekyll-archives
